apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: citus-coordinator
spec:
  selector:
    matchLabels:
      app: citus-coordinator
  serviceName: citus-coordinator
  replicas: 1
  template:
    metadata:
      labels:
        app: citus-coordinator
    spec:
      containers:
        - name: coordinator
          image: citusdata/citus:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres123
            - name: POSTGRES_DB
              value: citus
          volumeMounts:
            - name: coordinator-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: coordinator-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi