apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: parcial-final-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: parcial.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: parcial-frontend
                port:
                  number: 8000
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: parcial-backend
                port:
                  number: 8001
